-- ============================================================
-- TAB 3: berita
-- Jalankan KETIGA (setelah auth-profiles + kategori)
-- ============================================================


-- ─────────────────────────────────────────────────────────────
-- A. Helper: generate slug dari judul
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.generate_slug(input TEXT)
RETURNS TEXT AS $$
DECLARE
  result TEXT;
BEGIN
  result := TRIM(input);
  result := REGEXP_REPLACE(result, '[''`]',          '',  'g'); -- hapus apostrof
  result := REGEXP_REPLACE(result, '[-–—]',          ' ', 'g'); -- hyphen → spasi
  result := REGEXP_REPLACE(result, '[^a-zA-Z0-9\s]', '',  'g'); -- buang karakter khusus
  result := REGEXP_REPLACE(result, '\s+',            '-', 'g'); -- spasi → strip
  result := REGEXP_REPLACE(result, '-{2,}',          '-', 'g'); -- strip ganda → satu
  result := REGEXP_REPLACE(result, '^-+|-+$',        '',  'g'); -- strip di tepi
  RETURN LOWER(result);
END;
$$ LANGUAGE plpgsql;


-- ─────────────────────────────────────────────────────────────
-- B. Tabel berita
-- ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.berita (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  judul        TEXT NOT NULL,
  slug         TEXT UNIQUE,
  isi_berita   TEXT,
  gambar_url   TEXT,
  kategori_id  BIGINT REFERENCES public.kategori(id) ON DELETE SET NULL,
  penulis_id   UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  penulis_nama TEXT,                            -- di-sync otomatis dari profiles.name
  tags         TEXT[] DEFAULT '{}',
  status       TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
  published_at TIMESTAMP WITH TIME ZONE,
  created_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Safety: jika tabel sudah ada tapi kolom penulis_nama belum
ALTER TABLE public.berita ADD COLUMN IF NOT EXISTS penulis_nama TEXT;

ALTER TABLE public.berita ENABLE ROW LEVEL SECURITY;

-- Policies
DROP POLICY IF EXISTS "Publik baca published" ON public.berita;
DROP POLICY IF EXISTS "Admin baca semua"      ON public.berita;

CREATE POLICY "Publik baca published"
  ON public.berita FOR SELECT
  USING (status = 'published');

CREATE POLICY "Admin baca semua"
  ON public.berita FOR SELECT TO authenticated
  USING (true);


-- ─────────────────────────────────────────────────────────────
-- C. Trigger BEFORE INSERT/UPDATE berita
--    → auto-fill: penulis_id, penulis_nama, slug, updated_at
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.handle_berita_before_save()
RETURNS TRIGGER AS $$
DECLARE
  base_slug  TEXT;
  final_slug TEXT;
  counter    INTEGER := 1;
BEGIN
  -- Auto-fill penulis_id dari sesi user login
  IF NEW.penulis_id IS NULL THEN
    NEW.penulis_id := auth.uid();
  END IF;

  -- Auto-fill penulis_nama dari profiles
  IF NEW.penulis_nama IS NULL OR NEW.penulis_nama = '' THEN
    SELECT name INTO NEW.penulis_nama
    FROM public.profiles
    WHERE id = NEW.penulis_id;
  END IF;

  -- Auto-generate slug unik
  IF NEW.slug IS NULL OR NEW.slug = '' THEN
    base_slug  := public.generate_slug(NEW.judul);
    final_slug := base_slug;

    WHILE EXISTS (
      SELECT 1 FROM public.berita
      WHERE slug = final_slug
        AND id IS DISTINCT FROM NEW.id
    ) LOOP
      final_slug := base_slug || '-' || counter;
      counter    := counter + 1;
    END LOOP;

    NEW.slug := final_slug;
  END IF;

  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_berita_before_save ON public.berita;
CREATE TRIGGER trg_berita_before_save
  BEFORE INSERT OR UPDATE ON public.berita
  FOR EACH ROW EXECUTE FUNCTION public.handle_berita_before_save();


-- ─────────────────────────────────────────────────────────────
-- D. Trigger AFTER INSERT/UPDATE/DELETE berita
--    → update jumlah artikel per kategori
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.update_jumlah_kategori()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW.kategori_id IS NOT NULL AND NEW.status = 'published' THEN
      UPDATE public.kategori SET jumlah = jumlah + 1 WHERE id = NEW.kategori_id;
    END IF;

  ELSIF TG_OP = 'DELETE' THEN
    IF OLD.kategori_id IS NOT NULL AND OLD.status = 'published' THEN
      UPDATE public.kategori SET jumlah = jumlah - 1 WHERE id = OLD.kategori_id;
    END IF;

  ELSIF TG_OP = 'UPDATE' THEN

    -- draft → published
    IF OLD.status != 'published' AND NEW.status = 'published'
      AND NEW.kategori_id IS NOT NULL THEN
      UPDATE public.kategori SET jumlah = jumlah + 1 WHERE id = NEW.kategori_id;

    -- published → non-published
    ELSIF OLD.status = 'published' AND NEW.status != 'published'
      AND OLD.kategori_id IS NOT NULL THEN
      UPDATE public.kategori SET jumlah = jumlah - 1 WHERE id = OLD.kategori_id;

    -- pindah kategori (keduanya published)
    ELSIF OLD.status = 'published' AND NEW.status = 'published'
      AND OLD.kategori_id IS DISTINCT FROM NEW.kategori_id THEN
      IF OLD.kategori_id IS NOT NULL THEN
        UPDATE public.kategori SET jumlah = jumlah - 1 WHERE id = OLD.kategori_id;
      END IF;
      IF NEW.kategori_id IS NOT NULL THEN
        UPDATE public.kategori SET jumlah = jumlah + 1 WHERE id = NEW.kategori_id;
      END IF;
    END IF;

  END IF;

  RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS trg_jumlah_kategori ON public.berita;
CREATE TRIGGER trg_jumlah_kategori
  AFTER INSERT OR DELETE OR UPDATE OF kategori_id, status ON public.berita
  FOR EACH ROW EXECUTE FUNCTION public.update_jumlah_kategori();


-- ─────────────────────────────────────────────────────────────
-- E. Trigger AFTER UPDATE profiles
--    → sync penulis_nama ke semua berita milik penulis tsb
--    (diletakkan di sini karena butuh tabel berita sudah ada)
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.handle_profile_name_update()
RETURNS TRIGGER AS $$
BEGIN
  IF OLD.name IS DISTINCT FROM NEW.name THEN
    UPDATE public.berita
    SET penulis_nama = NEW.name
    WHERE penulis_id = NEW.id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_profile_name_update ON public.profiles;
CREATE TRIGGER trg_profile_name_update
  AFTER UPDATE OF name ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.handle_profile_name_update();


-- ─────────────────────────────────────────────────────────────
-- F. Backfill: isi penulis_nama untuk data berita yang sudah ada
-- ─────────────────────────────────────────────────────────────

UPDATE public.berita b
SET penulis_nama = p.name
FROM public.profiles p
WHERE b.penulis_id = p.id
  AND (b.penulis_nama IS NULL OR b.penulis_nama = '');