-- ========================================================================
-- 📄 BERKAS: 02_kategori.sql
-- Deskripsi: Modul 02 - Manajemen Kategori Berita
-- Urutan Eksekusi: Kedua (2)
-- ========================================================================

CREATE TABLE IF NOT EXISTS public.kategori (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_kategori TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  jumlah INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Mengaktifkan Row Level Security (RLS)
ALTER TABLE public.kategori ENABLE ROW LEVEL SECURITY;

-- Kebijakan Akses (RLS Policy): Ruang publik/awam bebas membaca data kategori
DROP POLICY IF EXISTS "Kategori boleh dibaca oleh ruang awam" ON public.kategori;
CREATE POLICY "Kategori boleh dibaca oleh ruang awam" 
ON public.kategori FOR SELECT USING (true);