-- ========================================================================
-- 📄 BERKAS: 03_berita.sql
-- Deskripsi: Modul 03 - Core Artikel Konten & Otomasi Engine
-- Syarat Jalankannya: Pastikan Berkas 01 dan Berkas 02 sudah sukses di-run
-- ========================================================================

CREATE TABLE IF NOT EXISTS public.berita (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  judul        TEXT NOT NULL,
  slug         TEXT UNIQUE,
  isi_berita   TEXT,
  gambar_url   TEXT,
  kategori_id  BIGINT REFERENCES public.kategori(id) ON DELETE SET NULL,
  penulis_id   UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  penulis_nama TEXT, -- ✅ Standar produksi: Langsung tertanam dari awal
  tags         TEXT[] DEFAULT '{}',
  status       TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
  published_at TIMESTAMP WITH TIME ZONE,
  created_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Mengaktifkan Row Level Security (RLS) untuk Berita
ALTER TABLE public.berita ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Publik baca published" ON public.berita;
DROP POLICY IF EXISTS "Admin baca semua" ON public.berita;

CREATE POLICY "Publik baca published" ON public.berita FOR SELECT USING (status = 'published');
CREATE POLICY "Admin baca semua" ON public.berita FOR SELECT TO authenticated USING (true);


-- ⚡ Fungsi Sistem 3.1: Slug Generator (Menghapus karakter aneh & konversi spasi ke strip untuk URL)
CREATE OR REPLACE FUNCTION public.generate_slug(input TEXT) RETURNS TEXT AS $$
DECLARE
  result TEXT;
BEGIN
  result := trim(input);
  result := regexp_replace(result, '[''`]',          '', 'g'); 
  result := regexp_replace(result, '[-–—]',          ' ', 'g'); 
  result := regexp_replace(result, '[^a-zA-Z0-9\s]', '', 'g'); 
  result := regexp_replace(result, '\s+',            '-', 'g'); 
  result := regexp_replace(result, '-{2,}',          '-', 'g'); 
  result := regexp_replace(result, '^-+|-+$',        '', 'g'); 
  RETURN lower(result);
END;
$$ LANGUAGE plpgsql;


-- ⚡ Otomasi Komponen 3.2: Mempersiapkan data sebelum draf disimpan (Set UID, Ambil Nama, & Amankan Duplikasi Slug)
CREATE OR REPLACE FUNCTION public.handle_berita_before_save()
RETURNS TRIGGER AS $$
DECLARE
  base_slug  TEXT;
  final_slug TEXT;
  counter    INTEGER := 1;
BEGIN
  -- Isi ID penulis secara otomatis dari session user yang sedang aktif di Supabase
  IF NEW.penulis_id IS NULL THEN
    NEW.penulis_id := auth.uid();
  END IF;

  -- Tarik data nama asli terbaru dari tabel profiles untuk menghindari query join yang berat di front-end
  IF NEW.penulis_nama IS NULL OR NEW.penulis_nama = '' THEN
    SELECT name INTO NEW.penulis_nama FROM public.profiles WHERE id = NEW.penulis_id;
  END IF;

  -- Otomatisasi pembentukan URL (slug) unik dengan proteksi perulangan (looping anti-bentrok)
  IF NEW.slug IS NULL OR NEW.slug = '' THEN
    base_slug  := public.generate_slug(NEW.judul);
    final_slug := base_slug;
    WHILE EXISTS (SELECT 1 FROM public.berita WHERE slug = final_slug AND id IS DISTINCT FROM NEW.id) LOOP
      final_slug := base_slug || '-' || counter;
      counter    := counter + 1;
    END LOOP;
    NEW.slug := final_slug;
  END IF;

  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_berita_before_save ON public.berita;
CREATE TRIGGER trg_berita_before_save BEFORE INSERT OR UPDATE ON public.berita
FOR EACH ROW EXECUTE FUNCTION public.handle_berita_before_save();


-- ⚡ Otomasi Komponen 3.3: Kalkulator Hitung Cerdas Jumlah Artikel Terpublikasi per Kategori (Real-time Metric)
CREATE OR REPLACE FUNCTION public.update_jumlah_kategori()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW.kategori_id IS NOT NULL AND NEW.status = 'published' THEN
      UPDATE public.kategori SET jumlah = jumlah + 1 WHERE id = NEW.kategori_id;
    END IF;
  ELSIF TG_OP = 'DELETE' THEN
    IF OLD.kategori_id IS NOT NULL AND OLD.status = 'published' THEN
      UPDATE public.kategori SET jumlah = jumlah - 1 WHERE id = OLD.kategori_id;
    END IF;
  ELSIF TG_OP = 'UPDATE' THEN
    IF OLD.status != 'published' AND NEW.status = 'published' AND NEW.kategori_id IS NOT NULL THEN
      UPDATE public.kategori SET jumlah = jumlah + 1 WHERE id = NEW.kategori_id;
    ELSIF OLD.status = 'published' AND NEW.status != 'published' AND OLD.kategori_id IS NOT NULL THEN
      UPDATE public.kategori SET jumlah = jumlah - 1 WHERE id = OLD.kategori_id;
    ELSIF OLD.status = 'published' AND NEW.status = 'published' AND OLD.kategori_id IS DISTINCT FROM NEW.kategori_id THEN
      IF OLD.kategori_id IS NOT NULL THEN
        UPDATE public.kategori SET jumlah = jumlah - 1 WHERE id = OLD.kategori_id;
      END IF;
      IF NEW.kategori_id IS NOT NULL THEN
        UPDATE public.kategori SET jumlah = jumlah + 1 WHERE id = NEW.kategori_id;
      END IF;
    END IF;
  END IF;
  RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS trg_jumlah_kategori ON public.berita;
CREATE TRIGGER trg_jumlah_kategori AFTER INSERT OR DELETE OR UPDATE OF kategori_id, status ON public.berita
FOR EACH ROW EXECUTE FUNCTION public.update_jumlah_kategori();


-- ⚡ Otomasi Lintas Modul 3.4: Sinkronisasi Data Nama Penulis Lintas Tabel
-- Jika di masa depan Admin mengubah namanya di menu pengaturan Profil, 
-- semua jejak artikel lamanya akan otomatis diperbarui namanya secara instan.
CREATE OR REPLACE FUNCTION public.handle_profile_name_update()
RETURNS TRIGGER AS $$
BEGIN
  IF OLD.name IS DISTINCT FROM NEW.name THEN
    UPDATE public.berita SET penulis_nama = NEW.name WHERE penulis_id = NEW.id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_profile_name_update ON public.profiles;
CREATE TRIGGER trg_profile_name_update AFTER UPDATE OF name ON public.profiles
FOR EACH ROW EXECUTE FUNCTION public.handle_profile_name_update();