-- 02. Kategori

CREATE TABLE IF NOT EXISTS kategori (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_kategori TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  jumlah INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

ALTER TABLE kategori ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Kategori boleh dibaca oleh ruang awam" ON kategori;
CREATE POLICY "Kategori boleh dibaca oleh ruang awam" 
ON kategori FOR SELECT 
USING (true);