-- 03. Berita
CREATE OR REPLACE FUNCTION generate_slug(input TEXT)
RETURNS TEXT AS $$
DECLARE
  result TEXT;
BEGIN
  result := trim(input);
  result := regexp_replace(result, '[''`]',          '', 'g'); -- 1. hapus apostrof
  result := regexp_replace(result, '[-–—]',          ' ', 'g'); -- 2. hyphen → spasi
  result := regexp_replace(result, '[^a-zA-Z0-9\s]', '', 'g'); -- 3. buang karakter lain
  result := regexp_replace(result, '\s+',            '-', 'g'); -- 4. spasi → strip
  result := regexp_replace(result, '-{2,}',          '-', 'g'); -- 5. strip ganda → satu
  result := regexp_replace(result, '^-+|-+$',        '', 'g'); -- 6. strip di tepi
  RETURN lower(result);
END;
$$ LANGUAGE plpgsql;

-- 2. Trigger function (HANYA SATU, versi dengan loop uniqueness)
CREATE OR REPLACE FUNCTION handle_berita_before_save()
RETURNS TRIGGER AS $$
DECLARE
  base_slug  TEXT;
  final_slug TEXT;
  counter    INTEGER := 1;
BEGIN
  -- ✅ Auto-fill penulis_id dari user yang login
  IF NEW.penulis_id IS NULL THEN
    NEW.penulis_id := auth.uid();
  END IF;

  IF NEW.slug IS NULL OR NEW.slug = '' THEN
    base_slug  := generate_slug(NEW.judul);
    final_slug := base_slug;

    WHILE EXISTS (
      SELECT 1 FROM berita
      WHERE slug = final_slug
        AND id IS DISTINCT FROM NEW.id
    ) LOOP
      final_slug := base_slug || '-' || counter;
      counter    := counter + 1;
    END LOOP;

    NEW.slug := final_slug;
  END IF;

  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 3. Tabel berita
CREATE TABLE IF NOT EXISTS berita (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  judul       TEXT NOT NULL,
  slug        TEXT UNIQUE,
  isi_berita  TEXT,
  gambar_url  TEXT,
  kategori_id BIGINT REFERENCES kategori(id) ON DELETE SET NULL,
  penulis_id  UUID   REFERENCES auth.users(id) ON DELETE SET NULL,
  tags        TEXT[] DEFAULT '{}',
  status      TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
  published_at TIMESTAMP WITH TIME ZONE,
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- 4. Trigger
DROP TRIGGER IF EXISTS trg_berita_before_save ON berita;
CREATE TRIGGER trg_berita_before_save
BEFORE INSERT OR UPDATE ON berita
FOR EACH ROW EXECUTE FUNCTION handle_berita_before_save();

-- 5. RLS
ALTER TABLE berita ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Publik baca published" ON berita;
DROP POLICY IF EXISTS "Admin baca semua" ON berita;

CREATE POLICY "Publik baca published" ON berita FOR SELECT USING (status = 'published');
CREATE POLICY "Admin baca semua" ON berita FOR SELECT TO authenticated USING (true);