-- Membina jadual kategori
CREATE TABLE kategori (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_kategori TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  jumlah INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Mengaktifkan ciri keselamatan Supabase (Row Level Security)
ALTER TABLE kategori ENABLE ROW LEVEL SECURITY;

-- Membenarkan semua pelawat web melihat senarai kategori ini
CREATE POLICY "Kategori boleh dibaca oleh ruang awam" 
ON kategori FOR SELECT 
USING (true);