-- Membuat tabel berita (posts)
CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Title & URL
  judul TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  
  -- Konten Berita
  isi_berita TEXT,
  gambar_url TEXT,
  
  -- Relasi (Category & Author)
  kategori_id BIGINT REFERENCES kategori(id) ON DELETE SET NULL,
  penulis_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  
  -- Tags
  tags TEXT[] DEFAULT '{}',
  
  -- Status & Date
  status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
  published_at TIMESTAMP WITH TIME ZONE,
  
  -- Sistem Tracking Waktu
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Mengaktifkan fitur keamanan (Row Level Security)
ALTER TABLE berita ENABLE ROW LEVEL SECURITY;

-- Kebijakan 1: Publik (pengunjung web) HANYA BISA melihat berita yang berstatus 'published'
CREATE POLICY "Pengunjung publik bisa membaca berita published" 
ON berita FOR SELECT 
USING (status = 'published');

-- Kebijakan 2: Admin/Staf yang sudah login bisa melihat semuanya (termasuk draft)
CREATE POLICY "Admin bisa melihat semua berita" 
ON berita FOR SELECT 
TO authenticated
USING (true);