-- ============================================================
-- TAB 2: kategori
-- Jalankan KEDUA (setelah auth-profiles)
-- ============================================================

-- 1. Tabel kategori
CREATE TABLE IF NOT EXISTS public.kategori (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_kategori TEXT NOT NULL,
  slug          TEXT NOT NULL UNIQUE,
  jumlah        INTEGER DEFAULT 0,
  created_at    TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

ALTER TABLE public.kategori ENABLE ROW LEVEL SECURITY;

-- 2. Policy: siapapun bisa baca kategori
DROP POLICY IF EXISTS "Kategori boleh dibaca oleh ruang awam" ON public.kategori;
CREATE POLICY "Kategori boleh dibaca oleh ruang awam"
  ON public.kategori FOR SELECT
  USING (true);