-- ============================================================
-- TAB 2: kategori
-- Jalankan KEDUA (setelah auth-profiles)
-- ============================================================

-- 1. Tabel kategori
CREATE TABLE IF NOT EXISTS public.kategori (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_kategori TEXT NOT NULL,
  slug          TEXT NOT NULL UNIQUE,
  jumlah        INTEGER DEFAULT 0 NOT NULL,
  created_at    TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

ALTER TABLE public.kategori ENABLE ROW LEVEL SECURITY;

-- 2. Policy: siapapun bisa baca kategori
DROP POLICY IF EXISTS "Kategori boleh dibaca oleh ruang awam" ON public.kategori;
CREATE POLICY "Kategori boleh dibaca oleh ruang awam"
  ON public.kategori FOR SELECT
  USING (true);

-- 3. Helper Function: Hitung & sinkronkan ulang jumlah berita published per kategori
CREATE OR REPLACE FUNCTION public.recalculate_kategori_jumlah()
RETURNS VOID AS $$
BEGIN
  UPDATE public.kategori k
  SET jumlah = COALESCE((
    SELECT COUNT(*)
    FROM public.berita b
    WHERE b.kategori_id = k.id
      AND b.status = 'published'
  ), 0);
END;
$$ LANGUAGE plpgsql;